### ISSUE TITLE
How to set ID for Primary key ??

### ISSUE THREAD

**Issue by ridergalau** [graknlabs/docs#120]
haii guys..
I Want to set ID for Primary key, but its so hard.
help me please guys..

**Comment by fppt** [comment]
Hi @ridergalau. We have seen you ask the same question [here](https://discuss.grakn.ai/t/how-to-set-id-for-primary-key/345/3) . 

We can continue the discussion there and try to help you out further. What exactly seems to be the problem?

**Comment by ridergalau** [comment]
oke wait...
i just find the other way
