### ISSUE TITLE
Comments for GRAKN.AI's "Get Started" documentation

### ISSUE THREAD

**Issue by stichbury** [graknlabs/docs#16]
Please leave comments about our "Get Started" documentation section here.

Insert usual disclaimer about being nice.

**Comment by stichbury** [comment]
I don't like that it opens in the same tab as the document.

**Comment by stichbury** [comment]
We can fix that.

**Comment by stichbury** [comment]
From @bolerio 

"This will start an instance of Cassandra which serves as the supported backend for Mindmaps."  

It starts also Engine which is an HTTP server providing batch loading, monitoring and the browser Dashboard (link to Dashboard docs). Engine should also be linked and documented. Every single element referred to for the first time should be linked to for more extensive reference documentation.

**Comment by stichbury** [comment]
Thanks for your comment @bolerio 

I have modified the text accordingly. When our api reference documentation is in place, I will point to the class reference for each element on its first mention. So this is only partly fixed for now.

**Comment by bolerio** [comment]
"If you intend to build Grakn, you will also need Maven 3." -- developing with Grakn (writing Java code)  requires Maven as well.

**Comment by bolerio** [comment]
"This will start an instance of Cassandra, which serves as the supported backend for Grakn. It starts also Grakn Engine, which is an HTTP server providing batch loading, monitoring and the browser dashboard." - lately it also starts kafka and zookeeper. It is worth mentioning so that people don't get surprises if they already have those tools on their default ports.

**Comment by bolerio** [comment]
After the example "./bin/graql.sh -f ./examples/basic-genealogy.gql", I would add "This starts the Graql shell in non-interactive mode, loading the specified file and exiting after the load is complete."

Then..."To start the command-line Graql shell in interactive mode, type:"

**Comment by bolerio** [comment]
"The visualiser allows you to make queries or simply browse the types within the graph." -- change "browse the types" to "browse the knowledge ontology".
