### ISSUE TITLE
Comments for GRAKN.AI's "The Basics" documentation

### ISSUE THREAD

**Issue by stichbury** [graknlabs/docs#17]
Please leave comments on our "The Basics" documentation section here.

Insert usual disclaimer about being nice.

**Comment by idealley** [comment]
# Ontology section

## Second paragraph
Typo: Grakn uses its our own declarative ontology language, Graql, and Grakn ontologies
remove: own

**Comment by burukuru** [comment]
Thanks @idealley. This has been fixed in our stable branch on the main repository. I'll check why it hasn't been pushed to the website.
