### ISSUE TITLE
Comments about Graph API Overview

### ISSUE THREAD

**Issue by stichbury** [graknlabs/docs#20]
Please leave comments about our [Graph API Overview](https://mindmaps.io/pages/documentation/core-api/overview.html) here.

Insert usual disclaimer about being nice.

**Comment by bolerio** [comment]
I would remove "It supports any Tinkerpop 3.0.z version." because this statement can easily become false depending on wherever development takes us and it's also a bit irrelevant since it pertains to how the software is deployed and what it's dependencies are (at the current implementation).

**Comment by stichbury** [comment]
Thanks @bolerio - I'll make that change.

**Comment by bolerio** [comment]
It might also be a good idea to have a separate page for development setup: "Setting up a Java project" or something like this where the maven dependencies and the intricacies of how we support different factories could be explained. If need more info on those intricacies, ask on Slack, but essentially the mindmaps server tells a client what the underlying implementation is supposed to be. The client has to be setup with the relevant dependencies (e.g. titan or orientdb or in memory or whatever), but it is the server that holds the deployment information. I will talk with Filipe to try and remove that need to run a server actually. I think Sheldon and Jason figured out a way to run Cassandra embedded...

**Comment by bolerio** [comment]
In the examples for adding resources to Alexander the Great seem outdated, the hasResource variable is used without having been declared before.
