### ISSUE TITLE
Comments for GRAKN.AI's "Developing with Java" documentation

### ISSUE THREAD

**Issue by stichbury** [graknlabs/docs#23]
Please leave any comments about the "Developing with Java" section here.

Insert usual disclaimer about being nice.

**Comment by emadkha** [comment]
i am using grakn 0.12.0 but LoaderClient not available in java .how can i solve this?

**Comment by alexandraorth** [comment]
Hi @emadkha. The `LoaderClient` is available in 0.12.0. It's in the `grakn-client` package. Have you added that dependency to your pom?

**Comment by emadkha** [comment]
hi @alexandraorth thank you  no , i have not added  that dependency because it is not declare in documentation.
please review documentation and update and debug it . thank you @alexandraorth  :+1: :+1:

**Comment by alexandraorth** [comment]
Glad it worked, and yes, we will definitely do that.
